### ISSUE TITLE
In debug50, move signal handling earlier to detect user hitting ctrl-c quite quickly after launch, which potentially raises a KeyboardError

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#13]
A la https://github.com/cs50/cli50/blob/main/cli50/__main__.py#L1-L4.

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cs50.vsix/commit/ce5cfdab1ecfb72c39f90740acdcb1649a052edb](https://github.com/cs50/cs50.vsix/commit/ce5cfdab1ecfb72c39f90740acdcb1649a052edb)
