### ISSUE TITLE
If possible, have debug50 check for breakpoints in all source files referenced in compiled binary

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#14]
I experimented with `nm`, `objdump`, and `readelf`, but the simplest way to get the full paths of source files used to build `main` seems to be `gdb`'s own `info` command:

https://github.com/cs50/cs50.vsix/blob/gdb/Makefile#L3

Demo can be used as follows:

```
git clone git@github.com:cs50/cs50.vsix.git
git checkout gdb
make
```

**Comment by dmalan** [comment]
Per @glennholloway:

```
dwarfdump ./main | grep DW_AT_decl_file
```

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cs50.vsix/commit/5bb7c6f0c9a0fa5aa3bb6ce5219fa9010d650914](https://github.com/cs50/cs50.vsix/commit/5bb7c6f0c9a0fa5aa3bb6ce5219fa9010d650914)
