### ISSUE TITLE
Move lab code to a lab50.vsix extension called CS50 Lab?

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#18]
https://github.com/cs50/lab50.vsix

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/341a33b9d730fe92ba02c2f70d26e55f08084862](https://github.com/cs50/lab50.vsix/commit/341a33b9d730fe92ba02c2f70d26e55f08084862)
