### ISSUE TITLE
Possible for `update50` to do a full-rebuild only when our image has changed and isn't yet cached, else a non-full-rebuild?

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#21]

**Comment by rongxin-liu** [comment]
When update50 prompts the user for an update, that means our image has changed, so always perform a full rebuild via update50 seems appropriate? An incremental rebuild (non-full-rebuild) uses the cached layer on the user's codespace and that's usually faster but gradually takes up the storage. A full rebuild would clear all the cached layers.

Though I did think about having update50 perform incremental rebuild by default and only perform a full rebuild when the cached layers take up too much storage.

**Comment by dmalan** [comment]
Hey, not sure I follow. If our image changes, and we only do an incremental
build, does that mean GH doesn't run `docker pull`? They *only* use
whatever image was originally pulled to re-create the container?

**Comment by rongxin-liu** [comment]
Per this documentation:
https://github.blog/changelog/2022-10-20-incremental-dev-container-rebuild/

Incremental rebuild builds on top of the existing docker cache, reusing common images and layers between rebuilds for a particular codespace. The main side effect would be taking up space gradually.

**Comment by dmalan** [comment]
Hm, that seems to imply that it does pull new layers, though, in which case an incremental rebuild would generally be much faster (unless our `Dockerfile` changes invalidates most/all of our layers), space aside?

**Comment by rongxin-liu** [comment]
I believe so. `update50` currently performs a full rebuild is mainly out of space concern.

**Comment by rongxin-liu** [comment]
Btw, to answer the question of this issue, do you mean if we could detect if GitHub has cached our cs50/codespace image (for faster container creation)? If so, I don't think there is a way to do it at the moment, at least [no API support](https://docs.github.com/en/rest/codespaces?apiVersion=2022-11-28).
