### ISSUE TITLE
Potential addition to install instructions: Adding link to instructions on setting up `code` command

### ISSUE THREAD

**Issue by pmalacho-mit** [cs50/cs50.vsix#27]
Hello! I was someone who hadn't added `code` to my `$PATH` variable. It might be helpful to add the following instructions to the readme (something like): 

> NOTE: If the above command gives the error `command not found: code`, you can follow [these instructions](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line) to enable launching VS Code from the command line.

**Comment by rongxin-liu** [comment]
Added instruction:
https://github.com/cs50/cs50.vsix/commit/84f324ae98ea94919cd6ebb21bd8781763b9bf2f
