### ISSUE TITLE
Possible to add these custom keybindings?

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#5]
```
[
  { "key": "ctrl+`", "command": "workbench.action.terminal.focus"},
  { "key": "ctrl+`", "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus"}
]
```

Per https://stackoverflow.com/a/43012779/5156190, https://stackoverflow.com/a/64343493/5156190.

**Comment by rongxin-liu** [comment]
Yes, we can contribute custom keybindings via the `package.json` file in our extension.
[https://github.com/cs50/cs50.vsix/commit/ca139077183350ea2b1e28c382acdb6ae5da2c7f](https://github.com/cs50/cs50.vsix/commit/ca139077183350ea2b1e28c382acdb6ae5da2c7f)
