### ISSUE TITLE
Try to programmatically remove default installation of ms-toolsai.jupyter as unnecessary

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#6]
@lostintangent, in case a student wants to re-install it after our removal, is there perhaps a way for us to distinguish between `ms-toolsai.jupyter` being installed as a dependency of `ms-python.python` (which we install via https://github.com/cs50/codespace/blob/main/.devcontainer.json#L5) versus a student manually installing it?

**Comment by rongxin-liu** [comment]
Achieved via extension-uninstaller.
