### ISSUE TITLE
Tidy UI when our extension loads

### ISSUE THREAD

**Issue by dmalan** [cs50/cs50.vsix#7]
1. `workbench.action.closeAllEditors`
1. `workbench.activityBar.visible = true`
1. `workbench.statusBar.visible = false`
1. `window.menuBarVisibility = false`

Not sure we'll want to do the first of those; might make more sense to have a button or shell command that restores the GUI to a known layout. But helpful to determine if we could do these, at least!

**Comment by rongxin-liu** [comment]
It is confirmed that we can do the first 3 and in fact, item 2 & 3 is already configured in our .devcontainer.json file. Item 4 doesn't seem to be a valid setting at this point.

**Comment by dmalan** [comment]
When are `.devcontainer.json`'s settings loaded, though? When you hit reload in a browser? Only when the container first starts? 

I.e., should we also put 2 and 3 in our extension so that they're always (re)set when a student reloads the browser (and thus our extension)?

**Comment by rongxin-liu** [comment]
According to [https://code.visualstudio.com/docs/remote/devcontainerjson-reference](https://code.visualstudio.com/docs/remote/devcontainerjson-reference), my understanding is that .devcontainer.json's setting is loaded when the container first starts and can be viewed as the cs50 default settings for users. Users can then change settings as they see fit.

It is possible that we can use our extension to enforce some settings each time VSCode reloads.

**Comment by dmalan** [comment]
Okay, want to try adding 2 and 3 to our extension, at which point we can perhaps remove them from `.devcontainer.json`?
