### ISSUE TITLE
Create a new terminal if there are no terminals in workspace

### ISSUE THREAD

**Issue by rongxin-liu** [cs50/cs50.vsix#9]
It would be nice if our extension could automatically focus on a terminal or create a new one if there is none as part of the UI tidying process.

**Comment by dmalan** [comment]
Is there an API call for detecting if terminal is open and for opening if not?

**Comment by dmalan** [comment]
Sounds reasonable!

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cs50.vsix/commit/aedb00fb7e0705bd0600c7196e0caf62d6bfff40](https://github.com/cs50/cs50.vsix/commit/aedb00fb7e0705bd0600c7196e0caf62d6bfff40)
